customer_id=101
type(customer_id)
customer_name="John"
type(customer_name)
bill_amount=675.45
type(bill_amount)
x=5.3+0.9j
type(x)
print(customer_id,customer_name,bill_amount)
print(x.real)
print(x.imag+3)
Flag=True
type(Flag)
y="False"
